spring:
  application:
    name: sales-api
  profiles:
    active: ${SPRING_PROFILE:dev}

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.sales.management: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
